config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "users#index"
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :comments_counter
  after_save :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.size)
  end
end

app/controllers/comment_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @user = User.find(params[:user_id])
  end

  def create
    post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params(post))

    if @comment.save
      flash[:alert] = 'New comment saved successfully'
      redirect_to user_posts_path
    else
      flash[:notice] = 'Error: Comment could not be saved'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params(post)
    a_comment = params.require(:comment).permit(:text)
    a_comment[:user] = current_user
    a_comment[:post] = post
    a_comment
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comment/_comment.html.erb
<p><%=comment.user.name %>: <%= comment.text %> </p>

app/views/comment/_form.html.erb
<div class="form_container">
<%= form_with model: comment, url: user_post_comments_url(user_id, post), method: :post, local: true, scope: :comment, class: 'form' do |f|%>
  <%= f.text_area :text %>
  <br>
  <%= f.submit "Comment" %>
<% end %>
</div> 

app/views/comment/new.html.erb
<div class="form_container">
<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, class: 'form' do |f|%>
  <%= f.text_area :text %>
  <br>
  <%= f.submit "Comment" %>
<% end %>
</div> 